import type { CardConfig } from '$lib/arcade/types.js';

export const CHARACTER_ROSTER: CardConfig[] = [
  {
    id: 'player-warrior',
    name: 'Warrior',
    attack: 80,
    defense: 60,
    health: 120,
    speed: 50,
    agility: 40,
    accuracy: 85,
    criticalChance: 15,
    element: 'PHYSICAL',
    skills: {
      special: {
        kind: 'ATTACK',
        name: 'Power Slash',
        damages: [{ type: 'PHYSICAL', rate: 2.0 }],
        energy: 3,
        targetingStrategy: 'position-based',
      },
      simpleAttack: {
        name: 'Strike',
        damages: [{ type: 'PHYSICAL', rate: 1.0 }],
        targetingStrategy: 'position-based',
      },
      others: [],
    },
    behaviors: { dodge: 'simple-dodge' },
  },
  {
    id: 'player-mage',
    name: 'Mage',
    attack: 100,
    defense: 30,
    health: 80,
    speed: 60,
    agility: 35,
    accuracy: 90,
    criticalChance: 20,
    element: 'FIRE',
    skills: {
      special: {
        kind: 'ATTACK',
        name: 'Fireball',
        damages: [{ type: 'FIRE', rate: 2.5 }],
        energy: 4,
        targetingStrategy: 'target-all',
      },
      simpleAttack: {
        name: 'Flame Bolt',
        damages: [
          { type: 'FIRE', rate: 0.7 },
          { type: 'PHYSICAL', rate: 0.3 },
        ],
        targetingStrategy: 'position-based',
      },
      others: [],
    },
    behaviors: { dodge: 'random-dodge' },
  },
  {
    id: 'player-healer',
    name: 'Healer',
    attack: 40,
    defense: 50,
    health: 100,
    speed: 55,
    agility: 45,
    accuracy: 80,
    criticalChance: 5,
    element: 'WATER',
    skills: {
      special: {
        kind: 'HEALING',
        name: 'Tidal Wave',
        rate: 1.5,
        energy: 3,
        targetingStrategy: 'all-allies',
      },
      simpleAttack: {
        name: 'Water Jet',
        damages: [{ type: 'WATER', rate: 1.0 }],
        targetingStrategy: 'position-based',
      },
      others: [
        {
          kind: 'HEALING',
          name: 'Mend',
          rate: 0.3,
          targetingStrategy: 'self',
          event: 'turn-end',
        },
      ],
    },
    behaviors: { dodge: 'simple-dodge' },
  },
  {
    id: 'player-rogue',
    name: 'Rogue',
    attack: 85,
    defense: 35,
    health: 85,
    speed: 90,
    agility: 70,
    accuracy: 88,
    criticalChance: 35,
    element: 'AIR',
    skills: {
      special: {
        kind: 'ATTACK',
        name: 'Shadow Flurry',
        damages: [
          { type: 'PHYSICAL', rate: 1.6 },
          { type: 'AIR', rate: 0.6 },
        ],
        energy: 3,
        targetingStrategy: 'position-based',
      },
      simpleAttack: {
        name: 'Quick Cut',
        damages: [{ type: 'PHYSICAL', rate: 1.0 }],
        targetingStrategy: 'position-based',
      },
      others: [],
    },
    behaviors: { dodge: 'random-dodge' },
  },
  {
    id: 'player-guardian',
    name: 'Guardian',
    attack: 45,
    defense: 90,
    health: 140,
    speed: 40,
    agility: 30,
    accuracy: 80,
    criticalChance: 5,
    element: 'EARTH',
    skills: {
      special: {
        kind: 'ATTACK',
        name: 'Bulwark Smash',
        damages: [{ type: 'EARTH', rate: 1.8 }],
        energy: 3,
        targetingStrategy: 'position-based',
      },
      simpleAttack: {
        name: 'Shield Bash',
        damages: [{ type: 'EARTH', rate: 1.0 }],
        targetingStrategy: 'position-based',
      },
      others: [
        {
          kind: 'ALTERATION',
          polarity: 'buff',
          name: 'Brace',
          rate: 0.25,
          targetingStrategy: 'all-allies',
          event: 'turn-end',
          buffType: 'defense',
          duration: 2,
        },
      ],
    },
    behaviors: { dodge: 'simple-dodge' },
  },
  {
    id: 'player-berserker',
    name: 'Berserker',
    attack: 120,
    defense: 25,
    health: 95,
    speed: 65,
    agility: 40,
    accuracy: 82,
    criticalChance: 25,
    element: 'PHYSICAL',
    skills: {
      special: {
        kind: 'ATTACK',
        name: 'Rampage',
        damages: [{ type: 'PHYSICAL', rate: 2.8 }],
        energy: 4,
        targetingStrategy: 'position-based',
      },
      simpleAttack: {
        name: 'Reckless Swing',
        damages: [{ type: 'PHYSICAL', rate: 1.2 }],
        targetingStrategy: 'position-based',
      },
      others: [],
    },
    behaviors: { dodge: 'simple-dodge' },
  },
  {
    id: 'player-frost-sage',
    name: 'Frost Sage',
    attack: 75,
    defense: 45,
    health: 90,
    speed: 58,
    agility: 40,
    accuracy: 90,
    criticalChance: 10,
    element: 'WATER',
    skills: {
      special: {
        kind: 'ATTACK',
        name: 'Glacial Spike',
        damages: [{ type: 'WATER', rate: 2.2 }],
        energy: 4,
        targetingStrategy: 'position-based',
      },
      simpleAttack: {
        name: 'Frost Touch',
        damages: [{ type: 'WATER', rate: 0.9 }],
        targetingStrategy: 'position-based',
        effects: [{ type: 'FREEZE', rate: 0.1, level: 1, probability: 0.3 }],
      },
      others: [],
    },
    behaviors: { dodge: 'simple-dodge' },
  },
  {
    id: 'player-storm-caller',
    name: 'Storm Caller',
    attack: 90,
    defense: 35,
    health: 85,
    speed: 70,
    agility: 50,
    accuracy: 87,
    criticalChance: 18,
    element: 'AIR',
    skills: {
      special: {
        kind: 'ATTACK',
        name: 'Chain Lightning',
        damages: [{ type: 'AIR', rate: 1.9 }],
        energy: 4,
        targetingStrategy: 'target-all',
      },
      simpleAttack: {
        name: 'Gust',
        damages: [
          { type: 'AIR', rate: 0.7 },
          { type: 'PHYSICAL', rate: 0.3 },
        ],
        targetingStrategy: 'position-based',
      },
      others: [],
    },
    behaviors: { dodge: 'random-dodge' },
  },
];

export const DEFAULT_DECK_IDS: string[] = CHARACTER_ROSTER.slice(0, 5).map(
  (card) => card.id,
);

export function findRosterCard(id: string): CardConfig | undefined {
  return CHARACTER_ROSTER.find((card) => card.id === id);
}
